name = "MittLeff"
uuid = "6498787a-c08e-48ed-b215-99219231320e"
authors = ["Victor Santos"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
